### ISSUE TITLE
Não foi possível testar as importações

### ISSUE THREAD

**Issue by Marinofull** [silvavinicyus/ratting-movies#1]
Não foi possível testar as importações pois não tinha documentação sobre o formato de arquivo, e qual a estrutura payload precisa estar no arquivo para realizar as importações. as mensagens de erro no console não dão informações sobre qual deveria ser a estrutura esperada.

**Comment by silvavinicyus** [comment]
Olá, Marino! Peço desculpas pelo vacilo!
Acabei de adicionar as informações dos tipos de arquivos para importação (json) e a estrutura necessária nos arquivos. Também adicionei <a href="https://github.com/silvavinicyus/ratting-movies-backend/tree/main/jsons"> aqui </a> dois arquivos exemplos para a importação dos filmes e notas.

**Comment by Marinofull** [comment]
Certo!
